### ISSUE TITLE
Änderungswunsch: Umlaute in Spaltennamen

### ISSUE THREAD

**Issue by hbruch** [mfdz/nvbw-haltestellen-issues#1]
Einige Spaltennamen der CSV-Datei enthalten Umlaute. Diese sind für die Weiterverarbeitung (z.B. Import in SQLite) unpraktisch und sollten durch Umschreibungen ersetzt werden.

**Comment by NVBWSeifert** [comment]
Wir kurzfristig umgesetzt, danke für den Hinweis

**Comment by NVBWSeifert** [comment]
Die Spaltennamen wurden angepasst

**Comment by hbruch** [comment]
Schlage vor, dass wir die Issues so lange offen lassen, bis korrigierte Version des Datensatzes veröffentlicht ist. Schließender Kommentar sollte das Datum der Veröffentlichung dieses Datensatzes beinhalten.

**Comment by NVBWSeifert** [comment]
ok. Der Datensatz wurde vor einigen Minuten veröffentlicht.
Kann ich dann trotzdem den Issue selbst schließen oder soll das der Issue-Ersteller machen (der ggfs. nicht reagiert, wenn er nur selten hier aktiv wäre)?

**Comment by hbruch** [comment]
Ah, Danke! Muss m.E. nicht der Issue-Ersteller machen. Sollte Problem fortbestehen/wieder auftreten, kann man ja erneut öffnen.

Schließe dann doch hier :-)
