### ISSUE TITLE
Schreibrechte für Issue Personen-Zuordnungen

### ISSUE THREAD

**Issue by NVBWSeifert** [mfdz/nvbw-haltestellen-issues#16]
Hallo,
kann ich Schreibrecht bekommen, um einen Issue einer zuständigen Person zuordnen zu können?
Ich möchte die meisten bzw. eigentlich alle Issues mir zuordnen, weil es ToDos für uns als NVBW sind

**Comment by hbruch** [comment]
Gerne! Invite ging gerade raus. 

Ich möchte dieses Repo zukünftig auch für individuelle Probleme bezogen auf einzelne Halte nutzen.
Perspektivisch wäre es m.E. sinnvoll, wenn auch die mit der Pflege betrauten Mitarbeiter*innnen das Repo nutzten.

Ich schließe jedoch schon mal diesen Issue.
