### ISSUE TITLE
Fehlende Angabe des Gültigkeitszeitraums für Steige

### ISSUE THREAD

**Issue by hbruch** [mfdz/nvbw-haltestellen-issues#8]
Wir vermuten, dass der Gültigkeitszeitraum für Steige nicht exportiert wurden und eventuell auch mittlerweile nicht mehr gültige Datensätze exportiert wurden (siehe auch #7)

Stand: 04.06.2019

**Comment by NVBWSeifert** [comment]
Ich werde die Felder mit exportieren, sie sind aber gar nicht oder in weniger als 1% der Fälle gefüllt.
Wir bemühen uns, das die Verantwortlichen die Gültigkeiten erfassen werden.

**Comment by hbruch** [comment]
Laut VDV432 (Abschnitt 2.3.1) sind auch Status und Betriebszustand zu erfassen. Sind diese eventuell besser gepflegt?

**Comment by NVBWSeifert** [comment]
Gültigkeitsfelder von und bis für Bereiche und Steige ergänzt in heutigem Update des Datensatzes.
Bisherige Beschränkung Ausgabe in engem Bezug zur Veröffentlichung aufgehoben, also generell Gültigkeitsausgabe, wenn vorhanden
